export default {
  horizontalLines: require('../animations/lines.json'),
  verticalLines: require('../animations/vertical-line.json'),
  crossLines: require('../animations/cross-line.json'),
  curv: require('../animations/curv.json'),
  rectangle: require('../animations/rectangle.json'),
  square: require('../animations/square.json'),
  triangle: require('../animations/triangle.json'),
  circles: require('../animations/circles.json'),
  ellipsis: require('../animations/ellipsis.json'),
  polygons: require('../animations/polygons.json'),
  cube: require('../animations/cube.json'),
  prism: require('../animations/3drectangular.json'),
  prisma: require('../animations/prisma.json'),
  cylinder: require('../animations/cylinder.json'),
  coffee: require('../animations/coffee.json'),
  chemicals: require('../animations/chemicals.json'),
  astronaut: require('../animations/astronaut.json'),
};
